
package cn.com.webxml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>中国邮政编码搜索 WEB 服务</strong>包含中国全部邮政编码共计187285条记录，是目前最完整的邮政编码数据，精确到乡镇级、城市精确到街道，支持邮政编码<->城市、乡镇、街道的双向查询。此邮政编码查询仅供参考，如邮政编码或地址有变动请以当地邮局为准，也请及时<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">通知我们</a>进行更正。<br />此邮政编码查询Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChinaZipSearchWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "file:/C:/Users/sjq/workspace/demo_two/src/ChinaZipSearchWebService.wsdl")
public class ChinaZipSearchWebService
    extends Service
{

    private final static URL CHINAZIPSEARCHWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHINAZIPSEARCHWEBSERVICE_EXCEPTION;
    private final static QName CHINAZIPSEARCHWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "ChinaZipSearchWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/sjq/workspace/demo_two/src/ChinaZipSearchWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHINAZIPSEARCHWEBSERVICE_WSDL_LOCATION = url;
        CHINAZIPSEARCHWEBSERVICE_EXCEPTION = e;
    }

    public ChinaZipSearchWebService() {
        super(__getWsdlLocation(), CHINAZIPSEARCHWEBSERVICE_QNAME);
    }

    public ChinaZipSearchWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHINAZIPSEARCHWEBSERVICE_QNAME, features);
    }

    public ChinaZipSearchWebService(URL wsdlLocation) {
        super(wsdlLocation, CHINAZIPSEARCHWEBSERVICE_QNAME);
    }

    public ChinaZipSearchWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHINAZIPSEARCHWEBSERVICE_QNAME, features);
    }

    public ChinaZipSearchWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChinaZipSearchWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChinaZipSearchWebServiceSoap
     */
    @WebEndpoint(name = "ChinaZipSearchWebServiceSoap")
    public ChinaZipSearchWebServiceSoap getChinaZipSearchWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaZipSearchWebServiceSoap"), ChinaZipSearchWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaZipSearchWebServiceSoap
     */
    @WebEndpoint(name = "ChinaZipSearchWebServiceSoap")
    public ChinaZipSearchWebServiceSoap getChinaZipSearchWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaZipSearchWebServiceSoap"), ChinaZipSearchWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHINAZIPSEARCHWEBSERVICE_EXCEPTION!= null) {
            throw CHINAZIPSEARCHWEBSERVICE_EXCEPTION;
        }
        return CHINAZIPSEARCHWEBSERVICE_WSDL_LOCATION;
    }

}
