
package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChinaZipSearchWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChinaZipSearchWebServiceSoap {


    /**
     * <br /><h3>获得本邮政编码查询Web Services支持的省份/直辖市信息</h3><p>输入参数：无； 返回数据：一个一维字符串数组 String()，内容为省份/直辖市的名称。</p><br />
     * 
     * @return
     *     returns cn.com.webxml.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getSupportProvince")
    @WebResult(name = "getSupportProvinceResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportProvince", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetSupportProvince")
    @ResponseWrapper(localName = "getSupportProvinceResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetSupportProvinceResponse")
    public ArrayOfString getSupportProvince();

    /**
     * <br /><h3>通过省份/直辖市查询本邮政编码查询Web Services支持的城市、地区信息</h3><p>输入参数：byProvinceName = 指定的省份/直辖市，若为空则默认上海；返回数据：一个一维字符串数组 String()，结构为：城市、地区(省份/直辖市)。</p><br />
     * 
     * @param byProvinceName
     * @return
     *     returns cn.com.webxml.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getSupportCity")
    @WebResult(name = "getSupportCityResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportCity", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetSupportCity")
    @ResponseWrapper(localName = "getSupportCityResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetSupportCityResponse")
    public ArrayOfString getSupportCity(
        @WebParam(name = "byProvinceName", targetNamespace = "http://WebXml.com.cn/")
        String byProvinceName);

    /**
     * <br /><h3>获得本邮政编码查询Web Services支持的全部省份/直辖市 和 城市、地区信息</h3><p>输入参数：空；返回数据：DataSet，结构为：Item.(CITY)=城市、地区，Item.(PROVINCE)=省份/直辖市。</p><br />
     * 
     * @return
     *     returns cn.com.webxml.GetSupportProvinceCityResponse.GetSupportProvinceCityResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getSupportProvinceCity")
    @WebResult(name = "getSupportProvinceCityResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportProvinceCity", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetSupportProvinceCity")
    @ResponseWrapper(localName = "getSupportProvinceCityResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetSupportProvinceCityResponse")
    public cn.com.webxml.GetSupportProvinceCityResponse.GetSupportProvinceCityResult getSupportProvinceCity();

    /**
     * <br /><h3>通过邮政编码查询本邮政编码查询Web Services支持地址数据</h3><p>输入参数：theZipCode = 中国的6位邮政编码，若为空则默认上海200080，userID = 商业用户ID（普通用户不需要）；返回数据：DataSet，结构为：Item.(ADDRESS)=街道、乡镇，Item.(CITY)=城市、地区，Item.(PROVINCE)=省份/直辖市，Item.(ZIP)=邮政编码。</p><br />
     * 
     * @param userID
     * @param theZipCode
     * @return
     *     returns cn.com.webxml.GetAddressByZipCodeResponse.GetAddressByZipCodeResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getAddressByZipCode")
    @WebResult(name = "getAddressByZipCodeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getAddressByZipCode", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetAddressByZipCode")
    @ResponseWrapper(localName = "getAddressByZipCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetAddressByZipCodeResponse")
    public cn.com.webxml.GetAddressByZipCodeResponse.GetAddressByZipCodeResult getAddressByZipCode(
        @WebParam(name = "theZipCode", targetNamespace = "http://WebXml.com.cn/")
        String theZipCode,
        @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
        String userID);

    /**
     * <br /><h3>通过省份、城市、地址查询本邮政编码查询Web Services支持邮政编码数据</h3><p>输入参数：theProvinceName = 省份/直辖市（必须按照 getSupportProvince 输入），theCityName = 城市、地区，theAddress = 街道、乡镇，userID = 商业用户ID（普通用户不需要），theProvinceName若为空则默认上海，支持模糊查询，免费用户最多输出20条相关数据（如需显示更多请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>）；返回数据：DataSet，结构为：Item.(ADDRESS)=街道、乡镇，Item.(CITY)=城市、地区，Item.(PROVINCE)=省份/直辖市，Item.(ZIP)=邮政编码。</p><br />
     * 
     * @param theCityName
     * @param theAddress
     * @param userID
     * @param theProvinceName
     * @return
     *     returns cn.com.webxml.GetZipCodeByAddressResponse.GetZipCodeByAddressResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getZipCodeByAddress")
    @WebResult(name = "getZipCodeByAddressResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getZipCodeByAddress", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetZipCodeByAddress")
    @ResponseWrapper(localName = "getZipCodeByAddressResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetZipCodeByAddressResponse")
    public cn.com.webxml.GetZipCodeByAddressResponse.GetZipCodeByAddressResult getZipCodeByAddress(
        @WebParam(name = "theProvinceName", targetNamespace = "http://WebXml.com.cn/")
        String theProvinceName,
        @WebParam(name = "theCityName", targetNamespace = "http://WebXml.com.cn/")
        String theCityName,
        @WebParam(name = "theAddress", targetNamespace = "http://WebXml.com.cn/")
        String theAddress,
        @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
        String userID);

}
