
package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidateCodeWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateCodeWebServiceSoap {


    /**
     * <br /><h3>直接获得验证码图片（小）</h3><p>输入参数：字符串，英文字母、符号或数字（为避免混淆请去除如：I 和 1 等，并转成大写），最多支持8个字符，如需要支持更多字符请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，默认随机输出4个字符图片； 返回数据：验证码图片。</p><br />
     * 
     * @param byString
     */
    @WebMethod(action = "http://WebXml.com.cn/smallValidateImage")
    @RequestWrapper(localName = "smallValidateImage", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.SmallValidateImage")
    @ResponseWrapper(localName = "smallValidateImageResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.SmallValidateImageResponse")
    public void smallValidateImage(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * <br /><h3>获得验证码图片字节数组（小）</h3><p>输入参数：字符串，英文字母、符号或数字（为避免混淆请去除如：I 和 1 等，并转成大写），最多支持8个字符，如需要支持更多字符请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，默认随机输出4个字符图片字节流； 返回数据：验证码图片字节流。</p><br />
     * 
     * @param byString
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://WebXml.com.cn/smallValidateByte")
    @WebResult(name = "smallValidateByteResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "smallValidateByte", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.SmallValidateByte")
    @ResponseWrapper(localName = "smallValidateByteResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.SmallValidateByteResponse")
    public byte[] smallValidateByte(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * <br /><h3>直接获得验证码图片（为英文/数字优化）</h3><p>输入参数：字符串，英文字母、符号或数字，最多支持8个字符，如需要支持更多字符请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，默认随机输出4个字符图片； 返回数据：验证码图片。</p><br />
     * 
     * @param byString
     */
    @WebMethod(action = "http://WebXml.com.cn/enValidateImage")
    @RequestWrapper(localName = "enValidateImage", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.EnValidateImage")
    @ResponseWrapper(localName = "enValidateImageResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.EnValidateImageResponse")
    public void enValidateImage(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * <br /><h3>获得验证码图片字节数组（为英文/数字优化）</h3><p>输入参数：字符串，英文字母、符号或数字，最多支持8个字符，如需要支持更多字符请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，默认随机输出4个字符图片字节流； 返回数据：验证码图片字节流。</p><br />
     * 
     * @param byString
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://WebXml.com.cn/enValidateByte")
    @WebResult(name = "enValidateByteResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "enValidateByte", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.EnValidateByte")
    @ResponseWrapper(localName = "enValidateByteResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.EnValidateByteResponse")
    public byte[] enValidateByte(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * <br /><h3>直接获得验证码图片（为中文字优化）</h3><p>输入参数：字符串，中文字，最多支持8个字，如需要支持更多字符请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，默认随机输出4个中文简体字图片； 返回数据：验证码图片。</p><br />
     * 
     * @param byString
     */
    @WebMethod(action = "http://WebXml.com.cn/cnValidateImage")
    @RequestWrapper(localName = "cnValidateImage", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.CnValidateImage")
    @ResponseWrapper(localName = "cnValidateImageResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.CnValidateImageResponse")
    public void cnValidateImage(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * <br /><h3>获得验证码图片字节数组（为中文字优化）</h3><p>输入参数：字符串，中文字，最多支持8个字，如需要支持更多字符请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，默认随机输出4个中文简体字图片字节流； 返回数据：验证码图片字节流。<br /><strong>字节流到图片可以参考以下方法</strong>（.NET vb）：<br />HttpContext.Current.Response.Cache.SetCacheability(System.Web.HttpCacheability.NoCache) '不缓存<br />HttpContext.Current.Response.ClearContent()<br />HttpContext.Current.Response.ContentType = "image/Png" '本服务输出Png类型<br />HttpContext.Current.Response.BinaryWrite(Ary) 'Ary 图片字节数组<br />HttpContext.Current.Response.End()</p><br />
     * 
     * @param byString
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://WebXml.com.cn/cnValidateByte")
    @WebResult(name = "cnValidateByteResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "cnValidateByte", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.CnValidateByte")
    @ResponseWrapper(localName = "cnValidateByteResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.CnValidateByteResponse")
    public byte[] cnValidateByte(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

}
